### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### getTarjetasALl
GET http://localhost:3000/api/v1/tarjetas

### getTarjetasAllByNumeroAndTitular
GET http://localhost:3000/api/v1/tarjetas?numero=9101-2345&titular=marius;

### getTarjetaById
GET http://localhost:3000/api/v1/tarjetas/1

### getTarjetaById(que no existe)
GET http://localhost:3000/api/v1/tarjetas/3

###Nueva tarjeta Bien
POST http://localhost:3000/api/v1/tarjetas
content-type: application/json

{
    "numero": "2222-5678-1234-5678",
    "cvc": "123",
    "fechaCaducidad" : "2029-12-31",
    "titular": "Maria",
    "saldo": 300.0
}

###Nueva tarjeta Mala validación
POST http://localhost:3000/api/v1/tarjetas
content-type: application/json

{
  "numero": "2222-5678-1234-5678",
  "cvc": "45s",
  "fechaCaducidad" : "2030-12-31",
  "titular": "Maria",
  "saldo": 300.0
}


### Actualiza tarjeta
PUT http://localhost:3000/api/v1/tarjetas/1
Content-Type: application/json

{
  "numero": "2222-5678-1234-5678",
  "cvc": "123",
  "fechaCaducidad": "2029-12-31",
  "titular": "María",
  "saldo": 300.0
}


### Delete tarjeta
DELETE http://localhost:3000/api/v1/tarjetas/2

