### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

### getTarjetasALl
GET http://localhost:3000/api/v1/tarjetas

### getTarjetasAllByNumeroAndTitular
GET http://localhost:3000/api/v1/tarjetas?numero=9101-2345&titular=marius;

### getTarjetaById
GET http://localhost:3000/api/v1/tarjetas/1

### getTarjetaById(que no existe)
GET http://localhost:3000/api/v1/tarjetas/3

